from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from urllib.parse import urlparse

import httpx

from app.core.config import Settings
from app.schemas import CreatePullRequestRequest, CreatePullRequestResponse
from app.services.fix_service import FixService
from app.services.run_store import RunStore


class GitHubService:
    def __init__(self, settings: Settings, run_store: RunStore, fix_service: FixService) -> None:
        self.settings = settings
        self.run_store = run_store
        self.fix_service = fix_service

    def create_pull_request(self, payload: CreatePullRequestRequest) -> CreatePullRequestResponse:
        repo_dir = self.run_store.run_dir(payload.run_id) / "repo"
        report = self.run_store.get_report(payload.run_id)
        modified_files = self.fix_service.modified_files(payload.run_id)
        if not modified_files:
            raise ValueError("No applied fixes are available to package into a pull request or patch.")

        git_executable = shutil.which("git")
        is_git_repo = git_executable is not None and (repo_dir / ".git").exists()
        branch_name = f"copilot/fixes-{payload.run_id[:8]}"
        title = payload.title or f"Apply Code Review Copilot fixes ({payload.run_id[:8]})"
        body = payload.body or "Automated fixes generated by the AI-Powered Code Review Copilot."

        if is_git_repo:
            commit_sha = self._commit_changes(git_executable, repo_dir, branch_name, title)
            patch_path = self._write_git_patch(git_executable, repo_dir, payload.run_id, commit_sha)
            pr_url = self._try_push_and_open_pr(
                git_executable=git_executable,
                repo_dir=repo_dir,
                branch_name=branch_name,
                base_branch=report.repository.default_branch,
                title=title,
                body=body,
            )
            if pr_url:
                return CreatePullRequestResponse(
                    run_id=payload.run_id,
                    mode="pull_request",
                    message="Created a branch, pushed the fixes, and opened a pull request.",
                    branch_name=branch_name,
                    pr_url=pr_url,
                    patch_path=str(patch_path),
                    modified_files=modified_files,
                )
            return CreatePullRequestResponse(
                run_id=payload.run_id,
                mode="patch",
                message="Committed the fixes locally and generated a patch because a remote pull request could not be created.",
                branch_name=branch_name,
                patch_path=str(patch_path),
                modified_files=modified_files,
            )

        patch_path = self._write_unified_patch(payload.run_id)
        return CreatePullRequestResponse(
            run_id=payload.run_id,
            mode="patch",
            message="Generated a patch file because this repository was not cloned as a writable git checkout.",
            patch_path=str(patch_path),
            modified_files=modified_files,
        )

    def _commit_changes(self, git_executable: str, repo_dir: Path, branch_name: str, title: str) -> str:
        self._run_git(git_executable, repo_dir, ["checkout", "-B", branch_name])
        self._run_git(git_executable, repo_dir, ["add", "-A"])
        self._run_git(
            git_executable,
            repo_dir,
            [
                "-c",
                "user.name=Code Review Copilot",
                "-c",
                "user.email=copilot@example.com",
                "commit",
                "-m",
                title,
            ],
        )
        return self._run_git(git_executable, repo_dir, ["rev-parse", "HEAD"]).stdout.strip()

    def _write_git_patch(self, git_executable: str, repo_dir: Path, run_id: str, commit_sha: str) -> Path:
        patch_dir = self.run_store.run_dir(run_id) / "artifacts"
        patch_dir.mkdir(parents=True, exist_ok=True)
        patch_path = patch_dir / "copilot-fixes.patch"
        result = self._run_git(git_executable, repo_dir, ["format-patch", "-1", commit_sha, "--stdout"])
        patch_path.write_text(result.stdout, encoding="utf-8")
        return patch_path

    def _write_unified_patch(self, run_id: str) -> Path:
        patch_dir = self.run_store.run_dir(run_id) / "artifacts"
        patch_dir.mkdir(parents=True, exist_ok=True)
        patch_path = patch_dir / "copilot-fixes.patch"
        patch_path.write_text(self.fix_service.build_patch_from_backups(run_id), encoding="utf-8")
        return patch_path

    def _try_push_and_open_pr(
        self,
        *,
        git_executable: str,
        repo_dir: Path,
        branch_name: str,
        base_branch: str,
        title: str,
        body: str,
    ) -> str | None:
        if not self.settings.github_token:
            return None

        remote_url = self._run_git(git_executable, repo_dir, ["remote", "get-url", "origin"]).stdout.strip()
        owner_repo = self._parse_owner_repo(remote_url)
        if not owner_repo:
            return None

        owner, repo = owner_repo
        push_target = self._tokenized_remote_url(remote_url)
        push_result = subprocess.run(
            [git_executable, "push", push_target, branch_name],
            cwd=repo_dir,
            capture_output=True,
            text=True,
            check=False,
        )
        if push_result.returncode != 0:
            return None

        headers = {
            "Authorization": f"Bearer {self.settings.github_token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
        }
        pr_payload = {
            "title": title,
            "body": body,
            "head": branch_name,
            "base": base_branch,
        }
        try:
            response = httpx.post(
                f"{self.settings.github_api_url}/repos/{owner}/{repo}/pulls",
                headers=headers,
                json=pr_payload,
                timeout=20.0,
            )
            response.raise_for_status()
            return response.json().get("html_url")
        except httpx.HTTPError:
            return None

    def _run_git(self, git_executable: str, repo_dir: Path, args: list[str]) -> subprocess.CompletedProcess[str]:
        result = subprocess.run(
            [git_executable, *args],
            cwd=repo_dir,
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            raise ValueError(result.stderr.strip() or result.stdout.strip() or "Git operation failed.")
        return result

    def _parse_owner_repo(self, remote_url: str) -> tuple[str, str] | None:
        if remote_url.startswith("git@github.com:"):
            path = remote_url.split(":", 1)[1]
        else:
            parsed = urlparse(remote_url)
            if "github.com" not in parsed.netloc:
                return None
            path = parsed.path.lstrip("/")
        if path.endswith(".git"):
            path = path[:-4]
        parts = path.split("/")
        if len(parts) < 2:
            return None
        return parts[0], parts[1]

    def _tokenized_remote_url(self, remote_url: str) -> str:
        parsed = urlparse(remote_url)
        if parsed.scheme in {"http", "https"} and parsed.netloc:
            return f"{parsed.scheme}://x-access-token:{self.settings.github_token}@{parsed.netloc}{parsed.path}"
        owner_repo = self._parse_owner_repo(remote_url)
        if not owner_repo:
            return remote_url
        owner, repo = owner_repo
        return f"https://x-access-token:{self.settings.github_token}@github.com/{owner}/{repo}.git"
